Rails.application.routes.draw do 
  get 'rooms/index'
  get 'roomtypes/index'
  get 'listhotels', to: 'hotels#index'
  get 'hotels/:id',to: 'hotels#show', as: 'hotels'
  get 'addhotels',to: 'hotels#new'
  post 'addhotels',to: 'hotels#create'
  get 'hotels/:id/edit', to: 'hotels#edit',as: 'edit_hotel'
  patch 'hotels/:id/edit',to: 'hotels#update'
  delete 'hotels/:id',to: 'hotels#destroy',as: 'delete_hotel'

  get 'listroomtypes' ,to: 'roomtypes#index'
  get 'roomtypes/:id',to: 'roomtypes#show', as: 'roomtypes'
  get 'addroomtypes',to: 'roomtypes#new'
  post 'addroomtypes',to: 'roomtypes#create'
  get 'roomtypes/:id/edit', to: 'roomtypes#edit',as: 'edit_roomtype'
  patch 'roomtypes/:id/edit',to: 'roomtypes#update'
  delete 'roomtypes/:id',to: 'roomtypes#destroy',as: 'delete_roomtype'

  get 'allotroom',to: 'rooms#index'
  get 'addguestandbooking' ,to: 'bookings#new'
  get 'addbookings' ,to: 'bookings#create'
  get '/bookings/:id',to: 'bookings#show',as: 'booking'
  get 'bills/new/:booking_id',to: 'bills#new',as:'new_booking_bill'
  post 'bills' ,to: 'bills#create',as: 'create_booking_bill'
  get '/bills/:id',to: 'bills#show',as: 'bill'
  get 'genbills',to: 'bills#payment'
  get 'feedbacks',to: 'feedbacks#new'
  post 'feedbacks',to: 'feedbacks#create'
  get 'addfeedbacks',to: 'feedbacks#create'
  post 'addfeedbacks',to: 'feedbacks#create'
  get 'thankyou',to: 'static_pages#thankyou'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'signup' ,to: 'users#new'

  get 'login',to: 'sessions#new'
  post 'login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'


  resources :users
  get 'users/:id',to: 'users#show', as: 'usersshow'
end
